### ISSUE TITLE
Noob question

### ISSUE THREAD

**Issue by emirmkd** [williamspiro/hubXml#41]
Hey, I'm sorry for putting this here, but I couldn't find any way to contact you otherwise.
I really want to use this, but I've never used Java before.
How do I run this? I think I set up all the right variables inside the files, but what's the next step(s)? I'm on a mac, but I can also do it on a windows if necessary.

Thanks and sorry again!

**Comment by williamspiro** [comment]
Closing this out but let me know if you have any questions @emirmkd !
